/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
import javax.swing.DefaultListModel;
import java.util.List;

/**
 *
 * @author AGIL
 */
public class JFrameUtama extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    private MysqlMahasiswaService service = new MysqlMahasiswaService();
    private DefaultListModel<String> dlmID = new DefaultListModel<>();
    private DefaultListModel<String> dlmNama = new DefaultListModel<>();

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
    initComponents();
    ListID.setModel(dlmID);
    ListNama.setModel(dlmNama);
    }

    private void refreshTable() {
        dlmID.clear();
        dlmNama.clear();
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa mhs : list) {
            dlmID.addElement(String.valueOf(mhs.getId()));
            dlmNama.addElement(mhs.getNama());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        LabelID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListNama = new javax.swing.JList<>();
        LabelNama = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        AmbilSemuaData = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        ButtonTambahkan = new javax.swing.JButton();
        IDEdit = new javax.swing.JTextField();
        NAMAEDIT = new javax.swing.JTextField();
        TextboxID2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ResetIndeks = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelID.setText("ID");

        ListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListID);

        ListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListNama);

        LabelNama.setText("Nama");

        Judul.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        Judul.setText("KelolaDataMahasiswa");

        AmbilSemuaData.setText("Ambil Semua Data");
        AmbilSemuaData.addActionListener(this::AmbilSemuaDataActionPerformed);

        jLabel4.setText("Nama:");

        ButtonTambahkan.setText("Tambahkan");
        ButtonTambahkan.addActionListener(this::ButtonTambahkanActionPerformed);

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(this::ButtonEditActionPerformed);

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(this::ButtonHapusActionPerformed);

        ResetIndeks.setText("Reset Indeks");
        ResetIndeks.addActionListener(this::ResetIndeksActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(LabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AmbilSemuaData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldNama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(IDEdit)
                                            .addComponent(TextboxID2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(NAMAEDIT))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ButtonEdit)
                                            .addComponent(ButtonHapus)))
                                    .addComponent(ResetIndeks)
                                    .addComponent(ButtonTambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 47, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNama)
                        .addGap(107, 107, 107)
                        .addComponent(Judul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(LabelNama)
                    .addComponent(Judul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AmbilSemuaData)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonTambahkan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAMAEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextboxID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(ResetIndeks)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahkanActionPerformed(java.awt.event.ActionEvent evt) {
    String nama = TextFieldNama.getText().trim();
    if (!nama.isEmpty()) {
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setNama(nama);
        service.add(mhs);
        refreshTable();
        TextFieldNama.setText("");
    }
}
    private void ResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetIndeksActionPerformed
        // TODO add your handling code here:
        service.indexReset();
        refreshTable();
        
    }//GEN-LAST:event_ResetIndeksActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        try {
        int id = Integer.parseInt(IDEdit.getText().trim());
        String nama = NAMAEDIT.getText().trim();
        if (!nama.isEmpty()) {
            Mahasiswa mhs = new Mahasiswa(id, nama);
            service.update(mhs);
            refreshTable();
            IDEdit.setText("");
            NAMAEDIT.setText("");
        }
    } catch (NumberFormatException e) {
        jLabel4.setText("ID tidak valid!");
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
            try {
        int id = Integer.parseInt(TextboxID2.getText().trim());
        service.delete(id);
        refreshTable();
        TextboxID2.setText("");
        jTextField5.setText("");
    } catch (NumberFormatException e) {
        jLabel4.setText("ID tidak valid!");
    }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void AmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        refreshTable();
        
    }//GEN-LAST:event_AmbilSemuaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmbilSemuaData;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonTambahkan;
    private javax.swing.JTextField IDEdit;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JList<String> ListID;
    private javax.swing.JList<String> ListNama;
    private javax.swing.JTextField NAMAEDIT;
    private javax.swing.JButton ResetIndeks;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextboxID2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
