/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihangui;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.LinkedHashMap;
/**
 *
 * @author AGIL
 */
public class GUI1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI1.class.getName());
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    List<String> itemList = new ArrayList<>();
    Set<String> itemSet = new LinkedHashSet<>();
    Map<String, String> itemMap = new LinkedHashMap<>();
    /**
     * Creates new form GUI
     */
    public GUI1() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jList1.setModel(dlm);
        jButton1.addActionListener(evt -> jButtonAddActionPerformed(evt));
        
        for (String data : datas) {
            dlm.addElement(data);
            updateJumlahDataTersimpan();
        }
    }
    
    private void updateJumlahDataTersimpan() {
        listLabel.setText("Data tersimpan = " + items.size());
    }
    
    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt){
        addItem(jTextField1.getText());
        
        jTextField1.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        saveToList = new javax.swing.JButton();
        insertDataList = new javax.swing.JButton();
        saveToSet = new javax.swing.JButton();
        insertDataSet = new javax.swing.JButton();
        saveToMap = new javax.swing.JButton();
        insertDataMap = new javax.swing.JButton();
        listLabel = new javax.swing.JLabel();
        setLabel = new javax.swing.JLabel();
        mapLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Item:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Clear All");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        saveToList.setText("Save to List ->");
        saveToList.addActionListener(this::saveToListActionPerformed);

        insertDataList.setText("<- Insert Data List");
        insertDataList.addActionListener(this::insertDataListActionPerformed);

        saveToSet.setText("Save to Set ->");
        saveToSet.addActionListener(this::saveToSetActionPerformed);

        insertDataSet.setText("<- Insert Data Set");
        insertDataSet.addActionListener(this::insertDataSetActionPerformed);

        saveToMap.setText("Save to Map ->");
        saveToMap.addActionListener(this::saveToMapActionPerformed);

        insertDataMap.setText("<- Insert Data Map");
        insertDataMap.addActionListener(this::insertDataMapActionPerformed);

        listLabel.setText("Data tersimpan = 0");

        setLabel.setText("Data tersimpan = 0");

        mapLabel.setText("Data tersimpan = 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(insertDataMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveToMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insertDataSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveToSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insertDataList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveToList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(listLabel)
                                        .addComponent(setLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(mapLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(424, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToList)
                            .addComponent(listLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToSet)
                            .addComponent(setLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertDataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToMap)
                            .addComponent(mapLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertDataMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String text = jTextField1.getText().trim();
        if (!text.isEmpty()) {
            dlm.addElement(text);
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        if (index >= 0) {
        dlm.removeElementAt(index);
        jTextField1.setText("");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        if (index >= 0) {
        String selected = jTextField1.getText().trim();
        if (!selected.isEmpty()) {
            dlm.setElementAt(selected, index);
            jTextField1.setText("");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    dlm.clear();
    jTextField1.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void saveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToListActionPerformed
        // TODO add your handling code here:
        itemList.clear();
    for (int i = 0; i < dlm.getSize(); i++) {
        itemList.add(dlm.getElementAt(i));
    }
        listLabel.setText("Data tersimpan = " + itemList.size());
    }//GEN-LAST:event_saveToListActionPerformed

    private void insertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataListActionPerformed
        // TODO add your handling code here:
        for (String item : itemList) {
        dlm.addElement(item);
    }
    }//GEN-LAST:event_insertDataListActionPerformed

    private void saveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToSetActionPerformed
        // TODO add your handling code here:
        itemSet.clear();
    for (int i = 0; i < dlm.getSize(); i++) {
        itemSet.add(dlm.getElementAt(i));
    }
    setLabel.setText("Data tersimpan = " + itemSet.size());
    }//GEN-LAST:event_saveToSetActionPerformed

    private void insertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataSetActionPerformed
        // TODO add your handling code here:
        for (String item : itemSet) {
        dlm.addElement(item);
        }
    }//GEN-LAST:event_insertDataSetActionPerformed

    private void saveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToMapActionPerformed
        // TODO add your handling code here:
        itemMap.clear();
    for (int i = 0; i < dlm.getSize(); i++) {
        String val = dlm.getElementAt(i);
        itemMap.put("item" + i, val);
    }
    mapLabel.setText("Data tersimpan = " + itemMap.size());
    }//GEN-LAST:event_saveToMapActionPerformed

    private void insertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataMapActionPerformed
        // TODO add your handling code here:
        for (String val : itemMap.values()) {
        dlm.addElement(val);
    }
    }//GEN-LAST:event_insertDataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insertDataList;
    private javax.swing.JButton insertDataMap;
    private javax.swing.JButton insertDataSet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel listLabel;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JButton saveToList;
    private javax.swing.JButton saveToMap;
    private javax.swing.JButton saveToSet;
    private javax.swing.JLabel setLabel;
    // End of variables declaration//GEN-END:variables
}
